---
# tasks file for roles/sudoers

- name: "PACKAGE | sudo"
  when: sudoers_install_sudo
  ansible.builtin.package:
    name: sudo
    state: present

- name: INCLUDE TASKS | 'manage_sudoers.yml' for groups
  loop: "{{ sudoers_groups }}"
  when:
    - sudoers_install_sudo
    - sudoers_manage_group_files
  ansible.builtin.include_tasks:
    file: manage_sudoers.yml

- name: INCLUDE TASKS | 'manage_sudoers.yml' for users
  loop: "{{ sudoers_users }}"
  when:
    - sudoers_install_sudo
    - sudoers_manage_user_files
  ansible.builtin.include_tasks:
    file: manage_sudoers.yml
